[package]
name = "databend-meta-types"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
anyerror = { workspace = true }
databend-meta-base = { workspace = true }
databend-meta-proto = { workspace = true }
deepsize = { workspace = true }
derive_more = { workspace = true }
display-more = { workspace = true }
log = { workspace = true }
map-api = { workspace = true }
num-traits = { workspace = true }
num_cpus = { workspace = true }
openraft = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
state-machine-api = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = { workspace = true }

[lints]
workspace = true
