[package]
name = "databend-meta-compat-new"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[[bin]]
name = "databend-meta-compat"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
databend-meta = { path = "../../../server/service" }
databend-meta-client = { path = "../../../client/client" }
databend-meta-runtime-api = { path = "../../../common/runtime-api" }
databend-meta-types = { path = "../../../server/types" }
env_logger = "0.11"
log = "0.4"
openraft = "=0.10.0-alpha.27"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.35", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
tonic = "0.13"

[patch.crates-io]
async-backtrace = { git = "https://github.com/datafuse-extras/async-backtrace.git", rev = "dea4553" }
databend-base = { git = "https://github.com/databendlabs/databend-base", tag = "v0.4.0" }
map-api = { git = "https://github.com/databendlabs/map-api", tag = "v0.4.2" }
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1" }
state-machine-api = { git = "https://github.com/databendlabs/state-machine-api.git", tag = "v0.3.4" }
watcher = { git = "https://github.com/databendlabs/watcher", tag = "v0.5.0" }
