[package]
name = "databend-meta-state-machine"
description = "The replicated state machine over the leveled store"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
databend-base = { workspace = true }
databend-meta-kvapi = { workspace = true }
databend-meta-leveled-store = { workspace = true }
databend-meta-metrics = { workspace = true }
databend-meta-raft-config = { workspace = true }
databend-meta-runtime-api = { workspace = true }
databend-meta-snapshot-db = { workspace = true }
databend-meta-snapshot-store = { workspace = true }
databend-meta-types = { workspace = true }
display-more = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
map-api = { workspace = true }
openraft = { workspace = true }
rotbl = { workspace = true }
seq-marked = { workspace = true }
serde_json = { workspace = true }
state-machine-api = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
databend-meta-leveled-store = { workspace = true, features = ["testing"] }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
