[package]
name = "databend-meta-version"
description = "Version information for databend-meta"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
semver = { workspace = true }

[dev-dependencies]
toml = { workspace = true }

[package.metadata.compat]
min-client-version = "1.2.676"
min-server-version = "260217.0.0"
min-raft-server-version = "1.2.818"
min-raft-client-version = "0.0.0"

[lints]
workspace = true
