// Copyright 2021 Datafuse Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! A builder to build a rotbl table from a series of sorted key-value.
//!
//! Committing it yields a plain table; wrapping that into a
//! [`DB`](databend_meta_snapshot_db::DB) is the snapshot store's job.

use std::io;
use std::path::Path;
#[cfg(test)]
use std::sync::Arc;

#[cfg(test)]
use databend_meta_snapshot_db::DB;
use databend_meta_types::sys_data::SysData;
use futures::Stream;
use futures_util::TryStreamExt;
use rotbl::storage::impls::fs::FsStorage;
use rotbl::v001::Rotbl;
use rotbl::v001::RotblMeta;
use rotbl::v001::SeqMarked;

#[cfg(test)]
use crate::leveled_store::leveled_map::LeveledMap;

/// Builds a snapshot from series of key-value in `(String, SeqMarked)`
pub(crate) struct DBBuilder {
    rotbl_builder: rotbl::v001::Builder<FsStorage>,
}

impl DBBuilder {
    pub fn new<P: AsRef<Path>>(
        storage_path: P,
        rel_path: &str,
        rotbl_config: rotbl::v001::Config,
    ) -> Result<Self, io::Error> {
        let storage = FsStorage::new(storage_path.as_ref().to_path_buf());

        let rel_path = rel_path.to_string();

        let inner = rotbl::v001::Builder::new(storage, rotbl_config, &rel_path)?;

        let b = Self {
            rotbl_builder: inner,
        };

        Ok(b)
    }

    /// Append a key-value pair to the builder, the keys must be sorted.
    pub fn append_kv(&mut self, k: String, v: SeqMarked) -> Result<(), io::Error> {
        self.rotbl_builder.append_kv(k, v)
    }

    /// This method is only used for test
    #[allow(dead_code)]
    pub async fn append_kv_stream(
        &mut self,
        strm: impl Stream<Item = Result<(String, SeqMarked), io::Error>>,
    ) -> Result<(), io::Error> {
        let mut strm = std::pin::pin!(strm);
        while let Some((k, v)) = strm.try_next().await? {
            self.append_kv(k, v)?;
        }
        Ok(())
    }

    /// The rotbl config the built table is written with.
    pub(crate) fn rotbl_config(&self) -> &rotbl::v001::Config {
        self.rotbl_builder.config()
    }

    /// Returns the base dir of the internal FS-storage.
    pub(crate) fn storage_path(&self) -> &str {
        self.rotbl_builder.storage().base_dir_str()
    }

    /// Commit the building.
    pub(crate) fn commit(self, sys_data: SysData) -> Result<(String, Rotbl), io::Error> {
        let meta = serde_json::to_string(&sys_data).map_err(|e| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!("serialize sys_data failed: {}", e),
            )
        })?;

        // the first arg `seq` is not used.
        let rotbl_meta = RotblMeta::new(0, meta);

        // The relative path of the built rotbl.
        let rel_path = self.rotbl_builder.rel_path().to_string();

        let r = self.rotbl_builder.commit(rotbl_meta)?;

        Ok((rel_path, r))
    }

    /// Build a [`DB`] from a leveled map.
    ///
    /// The DB contains all data in the leveled map and the snapshot id is generated by `make_snapshot_id`.
    ///
    /// Only used by tests.
    #[cfg(test)]
    pub async fn build_from_leveled_map(
        mut self,
        lm: &mut LeveledMap,
        make_snapshot_id: impl FnOnce(&SysData) -> String + Send,
    ) -> Result<DB, io::Error> {
        lm.freeze_writable_without_permit();

        let immutable_data = lm.immutable_data();
        let (sys_data, strm) = immutable_data.compact_into_stream().await?;

        self.append_kv_stream(strm).await?;

        let storage_path = self.storage_path().to_string();

        let snapshot_id = make_snapshot_id(&sys_data);
        let (rel_path, r) = self.commit(sys_data)?;
        let db = DB::new(storage_path, rel_path, snapshot_id, Arc::new(r))?;

        Ok(db)
    }
}

#[cfg(test)]
mod tests {
    use databend_meta_types::raft_types::new_log_id;
    use futures_util::TryStreamExt;
    use pretty_assertions::assert_eq;

    use super::*;

    fn sys_data() -> SysData {
        let mut sys_data = SysData::default();
        sys_data.update_seq(64);
        *sys_data.last_applied_mut() = Some(new_log_id(1, 2, 3));
        sys_data
    }

    fn kv(key: &str) -> (String, SeqMarked) {
        (
            key.to_string(),
            SeqMarked::new_normal(1, key.as_bytes().to_vec()),
        )
    }

    #[tokio::test]
    async fn test_commit_sorted_input() -> anyhow::Result<()> {
        let temp_dir = tempfile::tempdir()?;
        let storage_path = temp_dir.path().to_str().unwrap().to_string();

        let mut builder = DBBuilder::new(&storage_path, "temp-db", debug_checked_config())?;
        assert_eq!(builder.storage_path(), storage_path);

        builder
            .append_kv_stream(futures::stream::iter(["a", "b"].map(|k| Ok(kv(k)))))
            .await?;
        builder.append_kv("c".to_string(), SeqMarked::new_tombstone(2))?;

        let (rel_path, r) = builder.commit(sys_data())?;
        assert_eq!(rel_path, "temp-db");

        let db = DB::new(
            storage_path,
            rel_path,
            "snapshot-id".to_string(),
            Arc::new(r),
        )?;

        assert_eq!(db.sys_data, sys_data());
        assert_eq!(db.inner_range().try_collect::<Vec<_>>().await?, vec![
            kv("a"),
            kv("b"),
            ("c".to_string(), SeqMarked::new_tombstone(2)),
        ]);

        Ok(())
    }

    /// Out-of-order input is a caller bug, and `with_debug_check` makes
    /// the builder catch it instead of writing an unreadable table.
    #[test]
    #[should_panic(expected = "this key \"a\" must be greater than prev Some(\"b\")")]
    fn test_append_kv_rejects_out_of_order_keys() {
        let temp_dir = tempfile::tempdir().unwrap();

        let mut builder =
            DBBuilder::new(temp_dir.path(), "temp-db", debug_checked_config()).unwrap();

        builder
            .append_kv("b".to_string(), SeqMarked::new_tombstone(1))
            .unwrap();
        builder
            .append_kv("a".to_string(), SeqMarked::new_tombstone(2))
            .unwrap();
    }

    fn debug_checked_config() -> rotbl::v001::Config {
        rotbl::v001::Config::default().with_debug_check(true)
    }
}
