[package]
name = "databend-meta-snapshot-store"
description = "On-disk snapshot files: building, shipping and loading"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
databend-meta-leveled-store = { workspace = true }
databend-meta-raft-config = { workspace = true }
databend-meta-runtime-api = { workspace = true }
databend-meta-snapshot-db = { workspace = true }
databend-meta-types = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
openraft = { workspace = true }
rotbl = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
